name: ğŸ§¹ Cleanup Cancelled Runs

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  delete-cancelled:
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: ğŸ“‚ Get Code
        uses: actions/checkout@v4

      - name: ğŸ—‘ï¸ Delete Cancelled and Failed Runs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Loop back on statuses we want to delete
          for status in cancelled failure; do
            echo "Processing status: $status"
            # 1. Listing last 100 runs for the current status
            # 2. Get only their IDs
            # 3. Remove them one by one
            gh run list --status "$status" --limit 100 --json databaseId -q '.[].databaseId' | xargs -r -I{} gh run delete {}
          done
